### PR TITLE
Added PR video using Github Desktop

### PR DESCRIPTION
**Pull request by Npcodes1**
I added a new video about doing a pull request using GitHub Desktop.

### CODE REVIEW

**Comment by kacollins** [comment]
This is great, except that I was envisioning that this list would be of videos where members of our group gave talks. This would be better to add to the [hacktobherfest repo](https://github.com/shecodesokc/hacktobherfest#whats-a-pull-request)

**Comment by kacollins** [comment]
Thank you!

**Review by Npcodes1 — COMMENTED** [review]
Edited the hyperlink

**Comment by kacollins** [comment]
I already merged it in. You can fix this in a separate PR or we can let someone else do it :)

**Pull request merged**
